### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by smartkittynerd1** [smartkittynerd1/Hello-World#2]
I would like you to make a guess at what my favorite foods are and add them to the code as a comment if possible.

**Comment by Adam-Klemann** [comment]
I don't see any code, so I will add them here. My guesses are butterbeer and turkey legs. Remember to assign this issue to me since I have accepted the invite. You will see that on the righthand side in the "assignees" section.
![image](https://user-images.githubusercontent.com/11890053/134178833-d5058883-e6a6-45ba-96b8-66364911d59b.png)

**Comment by Adam-Klemann** [comment]
I would also make the description of the issue a sentence which describes what the bug, feature request, or todo item is. These are called "user stories" in many continuous development methodologies.

"Issue" is not descriptive.

**Comment by smartkittynerd1** [comment]
It wouldn't let me assign you to it earlier, but you have to accept my request to add you to the repository. Also, I wasn't sure what you wanted me to type as an issue since the link sent to me to make "my hello world code" didn't have me write any actual code.

**Comment by Adam-Klemann** [comment]
all complete. Good work!
